controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

home:
  path: "/app_home"
  controller: App\Controller\HomeController::homeIndex

register:
  path: "/app_register"
  controller: App\Controller\RegisterController::register

login:
  path: "/app_login"
  controller: App\Controller\SecurityController::login

category:
  path: "/category"
  controller: App\Controller\CategoryController::index

get_songs_by_category:
  path: /category/{id}/getsongs
  controller: App\Controller\CategoryController::getSongsByCategory
  methods: ["GET"]

song:
  path: "/song"
  controller: App\Controller\SongController::index

favorite:
  path: "/favorite"
  controller: App\Controller\FavoriteController::index

app_new_favorite:
  path : "favorite/newFavorite/{id}"
  controller: App\Controller\FavoriteController::newFavorite
  methods: ["GET"]

user:
  path: "/user"
  controller: App\Controller\UserController::index

player:
  path: /player/{id}/{category_id}
  controller: App\Controller\PlayerController::showSong
  requirements:
    id: \d+
    category_id: \d+

app_favorite_show:
  path: /favorites/{id}/show
  controller: App\Controller\FavoriteController::show
  methods: ["POST"]
